<?php
/**
 * Dealer Import Script
 * Run this script via: php import-dealers.php
 */

// Load WordPress
require_once dirname(__FILE__) . '/../../../wp-load.php';

// Dealer data from Excel
$dealers_data = [
    [
        'workshop_code' => 'AU01H',
        'dealer_company_code' => '8176927',
        'dealer_abn' => '56 602 706 874',
        'accounts_payable' => 'Sam Samarakoon',
        'email' => 'invoices@zeekrperth.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '08 9492 1332',
        'dealer_group' => 'Autoleague',
        'dealer_company_name' => 'AL VicPark Pty Ltd',
        'business_name' => 'ZEEKR Perth',
        'delivery_address_full' => '529 Albany Hwy, Victoria Park WA 6100',
        'delivery_address_street' => '529 Albany Hwy',
        'suburb' => 'Victoria Park',
        'state' => 'WA',
        'post_code' => '6100',
        'operating_hours_weekday' => '8:00 am - 5:00 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Marl Dacumos',
        'parts_manager_email' => 'marl.dacumos@zeekrperth.com.au',
        'parts_manager_mobile' => '0 450 680 502',
        'parts_manager_phone' => '08 9449 9449',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Darren Edmondson',
        'parts_interpreter_front_email' => 'darren.edmondson@zeekrperth.com.au',
        'parts_interpreter_front_mobile' => '0428 946 887',
        'parts_interpreter_front_phone' => '08 9449 9449',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'AU03H',
        'dealer_company_code' => '8169275',
        'dealer_abn' => '78 093 024 107',
        'accounts_payable' => 'Sharyn Ward',
        'email' => 'payables@jmcg.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '02 6122 2204',
        'dealer_group' => 'John McGrath',
        'dealer_company_name' => 'Mcgrath Canberra Pty Ltd',
        'business_name' => 'ZEEKR Canberra',
        'delivery_address_full' => '174 Melrose Dr, Phillip ACT 2606',
        'delivery_address_street' => '174 Melrose Dr',
        'suburb' => 'Phillip',
        'state' => 'ACT',
        'post_code' => '2606',
        'operating_hours_weekday' => '8:00 am - 5:00 pm',
        'operating_hours_saturday' => '8:00 am - 12:00 pm',
        'parts_manager' => 'Anthony Tadin',
        'parts_manager_email' => 'anthony.tadin@jmcg.com.au',
        'parts_manager_mobile' => 'N/A',
        'parts_manager_phone' => '02 6122 2220',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'N/A',
        'parts_interpreter_front_email' => 'N/A',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'Andrew Nelson',
        'parts_interpreter_back_email' => 'andrew.nelson@jmcg.com.au',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => '02 6122 2221',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'AU05H',
        'dealer_company_code' => '8182727',
        'dealer_abn' => '46 521 437 521',
        'accounts_payable' => 'Nathan Kerr',
        'email' => 'nkerr@southgate.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '08 8381 0700',
        'dealer_group' => 'SCL Automotive Group',
        'dealer_company_name' => 'SCL Sydney No1 Pty Ltd',
        'business_name' => 'ZEEKR Parramatta',
        'delivery_address_full' => '32 Church St, Parramatta NSW 2150',
        'delivery_address_street' => '32 Church St',
        'suburb' => 'Parramatta',
        'state' => 'NSW',
        'post_code' => '2150',
        'operating_hours_weekday' => '8:30 am - 5:00 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Michael Fordham',
        'parts_manager_email' => 'mfordham@zeekrparramatta.com.au',
        'parts_manager_mobile' => '0 424 961 442',
        'parts_manager_phone' => '02 8849 0055',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'N/A',
        'parts_interpreter_front_email' => 'N/A',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'AU02H',
        'dealer_company_code' => '8169271',
        'dealer_abn' => '92 102 974 274',
        'accounts_payable' => 'Group Email',
        'email' => 'ap.prestige.invoices@autosportsgroup.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '03 9550 5300',
        'dealer_group' => 'Autosports',
        'dealer_company_name' => 'ASG Prestige Cars Pty Ptd',
        'business_name' => 'ZEEKR Doncaster',
        'delivery_address_full' => '591 Doncaster Rd, Doncaster VIC 3108',
        'delivery_address_street' => '591 Doncaster Rd',
        'suburb' => 'Doncaster',
        'state' => 'VIC',
        'post_code' => '3108',
        'operating_hours_weekday' => '8:30 am - 5:30 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Jim Sheppard',
        'parts_manager_email' => 'jim.sheppard@volvocarsdoncaster.com.au',
        'parts_manager_mobile' => '0 416 479 161',
        'parts_manager_phone' => '03 9998 2265',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Gaganjot Singh',
        'parts_interpreter_front_email' => 'gaganjot.singh@volvocarsdoncaster.com.au',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => '03 9898 2265',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'ZAU015P',
        'dealer_company_code' => '8169271',
        'dealer_abn' => '92 102 974 274',
        'accounts_payable' => 'Group Email',
        'email' => 'ap.prestige.invoices@autosportsgroup.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '03 9550 5300',
        'dealer_group' => 'Autosports',
        'dealer_company_name' => 'ASG Prestige Cars Pty Ptd',
        'business_name' => 'ZEEKR South Yarra',
        'delivery_address_full' => '441 Malvern Rd, South Yarra VIC 3141',
        'delivery_address_street' => '441 Malvern Rd',
        'suburb' => 'South Yarra',
        'state' => 'VIC',
        'post_code' => '3141',
        'operating_hours_weekday' => '8:30 am - 5:30 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Elliot McHaffie',
        'parts_manager_email' => 'elliot.mchaffie@volvocarssy.com.au',
        'parts_manager_mobile' => 'N/A',
        'parts_manager_phone' => '03 9998 3796',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'N/A',
        'parts_interpreter_front_email' => 'parts@volvocarssouthyarra.com.au',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'AU01S',
        'dealer_company_code' => '8169269',
        'dealer_abn' => '75 006 175 515',
        'accounts_payable' => 'Paula Vasilj',
        'email' => 'accpay@gorell.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '03 5227 4675',
        'dealer_group' => 'Rex Gorell Group',
        'dealer_company_name' => 'Rex Gorell Ford Pty Ltd',
        'business_name' => 'ZEEKR Geelong',
        'delivery_address_full' => '20-26 Fyans St, Geelong VIC 3220',
        'delivery_address_street' => '20-26 Fyans St',
        'suburb' => 'Geelong',
        'state' => 'VIC',
        'post_code' => '3220',
        'operating_hours_weekday' => '8:00 am - 5:30 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Mario Dimasi',
        'parts_manager_email' => 'mdimasi@gorell.com.au',
        'parts_manager_mobile' => '0 412 186 308',
        'parts_manager_phone' => '03 5244 2885',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Sam Trueman',
        'parts_interpreter_front_email' => 'strueman@gorell.com.au',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => '03 5227 4534',
        'parts_interpreter_back' => 'Mark Pelham',
        'parts_interpreter_back_email' => 'mpelham@gorell.com.au',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => '03 5227 4532',
        'parts_group' => 'Parts Group',
        'parts_group_email' => 'parts@gorell.com.au',
        'parts_group_mobile' => 'N/A',
        'parts_group_phone' => '03 5221 2811',
    ],
    [
        'workshop_code' => 'AU02C',
        'dealer_company_code' => '8207597',
        'dealer_abn' => '75 633 200 512',
        'accounts_payable' => 'Robbie Chen',
        'email' => 'robbie.chen@zeekrsydneycity.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '02 7256 6667',
        'dealer_group' => 'Zhilian',
        'dealer_company_name' => 'Zhilian New Energy ZK Auto (Sydney) Pty Ltd',
        'business_name' => 'ZEEKR Sydney City',
        'delivery_address_full' => '1037-1047 Bourke St, Waterloo NSW 2017',
        'delivery_address_street' => '1037-1047 Bourke St',
        'suburb' => 'Waterloo',
        'state' => 'NSW',
        'post_code' => '2017',
        'operating_hours_weekday' => '8:30 am - 4:30 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Leslie Weng',
        'parts_manager_email' => 'leslie.weng@zeekrsydneycity.com.au',
        'parts_manager_mobile' => '0 425 309 700',
        'parts_manager_phone' => '02 5344 8888',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Avikash Siwan',
        'parts_interpreter_front_email' => 'avikash.siwan@zeekrsydneycity.com.au',
        'parts_interpreter_front_mobile' => '0 404 299 182',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'ZAU020S',
        'dealer_company_code' => '8207597',
        'dealer_abn' => '07 563 320 052',
        'accounts_payable' => 'Robbie Chen',
        'email' => 'robbie.chen@zeekrsydneycity.com.au',
        'mobile_phone' => '0 416 582 126',
        'phone' => '02 7256 6667',
        'dealer_group' => 'Zhilian',
        'dealer_company_name' => 'Zhilian New Energy ZK Auto (Sydney) Pty Ltd',
        'business_name' => 'ZEEKR Chatswood',
        'delivery_address_full' => 'Shop 1/1015 Pacific Hwy, Roseville NSW 2069',
        'delivery_address_street' => 'Shop 1/1015 Pacific Hwy',
        'suburb' => 'Roseville',
        'state' => 'NSW',
        'post_code' => '2069',
        'operating_hours_weekday' => '9:00 am - 5:00 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Leslie Weng',
        'parts_manager_email' => 'leslie.weng@zeekrsydneycity.com.au',
        'parts_manager_mobile' => '0 425 309 700',
        'parts_manager_phone' => '02 7256 6667',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Junaid Azeem',
        'parts_interpreter_front_email' => 'junaid.azeem@zeekrsydneycity.com.au',
        'parts_interpreter_front_mobile' => '',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'ZAU017P',
        'dealer_company_code' => '8206769',
        'dealer_abn' => '18 165 856 726',
        'accounts_payable' => 'Maria Blanco',
        'email' => 'accounts.payable@crickshighway.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '07 3808 1111',
        'dealer_group' => 'Autopact',
        'dealer_company_name' => 'Cricks Springwood Pty Ltd',
        'business_name' => 'ZEEKR Springwood',
        'delivery_address_full' => '1 Westerway St, Springwood QLD 4127',
        'delivery_address_street' => '1 Westerway St',
        'suburb' => 'Springwood',
        'state' => 'QLD',
        'post_code' => '4127',
        'operating_hours_weekday' => '8:00 am - 4:00 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Gavin Sadler',
        'parts_manager_email' => 'gavin.sadler@crickshighway.com.au',
        'parts_manager_mobile' => '0 422 233 588',
        'parts_manager_phone' => '07 3290 7890',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Joshua Corrie',
        'parts_interpreter_front_email' => 'joshua.corrie@crickshighway.com.au',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => '07 3290 7890',
        'parts_interpreter_back' => 'Grant Burgess',
        'parts_interpreter_back_email' => 'grant.burgess@crickshighway.com.au',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => '07 3290 7890',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'ZAU016P',
        'dealer_company_code' => '8198221',
        'dealer_abn' => '23 654 794 748',
        'accounts_payable' => 'Anthony Green',
        'email' => 'accounts.payable@cricks.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '07 5450 3300',
        'dealer_group' => 'Autopact',
        'dealer_company_name' => 'Garry Cricks Nambour Pty Ltd',
        'business_name' => 'ZEEKR Sunshine Coast',
        'delivery_address_full' => '88 Sugar Rd, Maroochydore QLD 4558',
        'delivery_address_street' => '88 Sugar Rd',
        'suburb' => 'Maroochydore',
        'state' => 'QLD',
        'post_code' => '4558',
        'operating_hours_weekday' => '8:00 am - 5:00 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Greg Lockyer',
        'parts_manager_email' => 'greg.lockyer@cricks.com.au',
        'parts_manager_mobile' => '0 405 411 572',
        'parts_manager_phone' => '07 5450 3300',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Josh Schilds',
        'parts_interpreter_front_email' => 'Joshua.schilds@cricks.com.au',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => '07 5450 3300',
        'parts_interpreter_back' => 'Damien Erlandson',
        'parts_interpreter_back_email' => 'damien.erlandson@cricks.com.au',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => '07 5450 3300',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'ZAU018P',
        'dealer_company_code' => '8216155',
        'dealer_abn' => '76 684 304 318',
        'accounts_payable' => 'Emma Du',
        'email' => 'payable@smallworld-qld.com.au',
        'mobile_phone' => '0 424 000 838',
        'phone' => '02 8346 6000',
        'dealer_group' => 'Greentech',
        'dealer_company_name' => 'Small World QLD Pty Ltd',
        'business_name' => 'ZEEKR Centre Brisbane',
        'delivery_address_full' => '433 Gympie Rd, Kedron QLD 4031',
        'delivery_address_street' => '433 Gympie Rd',
        'suburb' => 'Kedron',
        'state' => 'QLD',
        'post_code' => '4031',
        'operating_hours_weekday' => '8:30 am - 4:00 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Patrick Ma',
        'parts_manager_email' => 'salesgm@zeekrcentrebrisbane.com.au',
        'parts_manager_mobile' => '0 428 776 798',
        'parts_manager_phone' => 'N/A',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'Byungkuk Lee',
        'parts_interpreter_front_email' => 'ZeekrServiceSuper@zeekrcentrebrisbane.com.au',
        'parts_interpreter_front_mobile' => '0411 236 736',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'ZAU025P',
        'dealer_company_code' => '8264624',
        'dealer_abn' => '81 107 070 988',
        'accounts_payable' => 'Tamir Kayal',
        'email' => 'accounts.payable@solitaire.com.au',
        'mobile_phone' => 'N/A',
        'phone' => '08 8274 5583',
        'dealer_group' => 'Solitaire',
        'dealer_company_name' => 'Russleigh Pty Ltd (Solitaire Automotive Group)',
        'business_name' => 'ZEEKR Adelaide',
        'delivery_address_full' => '67 London Rd, Mile End SA 5031',
        'delivery_address_street' => '67 London Rd',
        'suburb' => 'Mile End',
        'state' => 'SA',
        'post_code' => '5031',
        'operating_hours_weekday' => '8:00 am - 5:30 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Brenton Nanasi',
        'parts_manager_email' => 'brenton.nanasi@solitaire.com.au',
        'parts_manager_mobile' => '0 410 663 603',
        'parts_manager_phone' => '08 8152 5112',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'N/A',
        'parts_interpreter_front_email' => 'N/A',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
    [
        'workshop_code' => 'ZNZ001P',
        'dealer_company_code' => 'N/A',
        'dealer_abn' => '9429 052 733 437',
        'accounts_payable' => 'Pee Jay De Los Reyes',
        'email' => 'zeekr.accounts@nordeast.nz',
        'mobile_phone' => 'N/A',
        'phone' => '+64 9 526 2728',
        'dealer_group' => '',
        'dealer_company_name' => 'ZK Vehicle Importers Ltd',
        'business_name' => 'ZEEKR New Zealand',
        'delivery_address_full' => '120 Pavilion Drive, Mangere Auckland 2022, New Zealand',
        'delivery_address_street' => '120 Pavilion Drive',
        'suburb' => 'Mangere',
        'state' => 'Auckland',
        'post_code' => '2022, New Zealand',
        'operating_hours_weekday' => '8:30 am - 5:30 pm',
        'operating_hours_saturday' => 'Closed',
        'parts_manager' => 'Euan McHarg',
        'parts_manager_email' => 'emcharg@nordeast.nz',
        'parts_manager_mobile' => '+64 21 673 994',
        'parts_manager_phone' => 'N/A',
        'tis_access' => 'YES',
        'ordering_system' => '',
        'parts_interpreter_front' => 'N/A',
        'parts_interpreter_front_email' => 'N/A',
        'parts_interpreter_front_mobile' => 'N/A',
        'parts_interpreter_front_phone' => 'N/A',
        'parts_interpreter_back' => 'N/A',
        'parts_interpreter_back_email' => 'N/A',
        'parts_interpreter_back_mobile' => 'N/A',
        'parts_interpreter_back_phone' => 'N/A',
        'parts_group' => '',
        'parts_group_email' => '',
        'parts_group_mobile' => '',
        'parts_group_phone' => '',
    ],
];

echo "Starting dealer import...\n\n";

$created = 0;
$updated = 0;
$skipped = 0;
$errors = 0;

foreach ($dealers_data as $dealer) {
    // Determine username: use dealer_company_code, fallback to email
    $username = !empty($dealer['dealer_company_code']) && $dealer['dealer_company_code'] !== 'N/A'
        ? $dealer['dealer_company_code']
        : $dealer['email'];

    if (empty($username) || $username === 'N/A') {
        echo "SKIP: No username available for {$dealer['business_name']}\n";
        $skipped++;
        continue;
    }

    $email = $dealer['email'];
    if (empty($email) || $email === 'N/A' || !is_email($email)) {
        echo "SKIP: Invalid email for {$dealer['business_name']}\n";
        $skipped++;
        continue;
    }

    // Check if user already exists
    $existing_user = get_user_by('login', $username);
    if (!$existing_user) {
        $existing_user = get_user_by('email', $email);
    }

    if ($existing_user) {
        // Update existing user
        $user_id = $existing_user->ID;
        echo "UPDATE: User {$username} already exists (ID: {$user_id})\n";
        $updated++;
    } else {
        // Create new user
        $password = wp_generate_password(12, true);
        $user_id = wp_create_user($username, $password, $email);

        if (is_wp_error($user_id)) {
            echo "ERROR: Failed to create user {$username}: " . $user_id->get_error_message() . "\n";
            $errors++;
            continue;
        }

        echo "CREATE: User {$username} created (ID: {$user_id}) - Password: {$password}\n";
        $created++;
    }

    // Set role to dealer
    $user = new WP_User($user_id);
    $user->set_role('dealer');

    // Update display name
    wp_update_user([
        'ID' => $user_id,
        'display_name' => $dealer['business_name'],
        'first_name' => $dealer['accounts_payable'],
    ]);

    // Save all dealer meta data
    $meta_fields = [
        'workshop_code',
        'dealer_company_code',
        'dealer_abn',
        'accounts_payable',
        'mobile_phone',
        'phone',
        'dealer_group',
        'dealer_company_name',
        'business_name',
        'delivery_address_full',
        'delivery_address_street',
        'suburb',
        'state',
        'post_code',
        'operating_hours_weekday',
        'operating_hours_saturday',
        'parts_manager',
        'parts_manager_email',
        'parts_manager_mobile',
        'parts_manager_phone',
        'tis_access',
        'ordering_system',
        'parts_interpreter_front',
        'parts_interpreter_front_email',
        'parts_interpreter_front_mobile',
        'parts_interpreter_front_phone',
        'parts_interpreter_back',
        'parts_interpreter_back_email',
        'parts_interpreter_back_mobile',
        'parts_interpreter_back_phone',
        'parts_group',
        'parts_group_email',
        'parts_group_mobile',
        'parts_group_phone',
    ];

    foreach ($meta_fields as $field) {
        if (isset($dealer[$field])) {
            update_user_meta($user_id, 'dealer_' . $field, $dealer[$field]);
        }
    }

    // Also save billing address for WooCommerce
    update_user_meta($user_id, 'billing_company', $dealer['dealer_company_name']);
    update_user_meta($user_id, 'billing_address_1', $dealer['delivery_address_street']);
    update_user_meta($user_id, 'billing_city', $dealer['suburb']);
    update_user_meta($user_id, 'billing_state', $dealer['state']);
    update_user_meta($user_id, 'billing_postcode', $dealer['post_code']);
    update_user_meta($user_id, 'billing_phone', $dealer['phone']);
    update_user_meta($user_id, 'billing_email', $dealer['email']);
}

echo "\n========================================\n";
echo "Import completed!\n";
echo "Created: {$created}\n";
echo "Updated: {$updated}\n";
echo "Skipped: {$skipped}\n";
echo "Errors: {$errors}\n";
echo "========================================\n";
